services:
    nginx:
        restart: always
        image: nginx:1.23-alpine
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./data/web/static:/app/data/web/static
            - ./data/web/media:/app/data/web/media
    server:
        restart: always
        build:
            context: .
            dockerfile: ./Dockerfile
        entrypoint: /app/docker/project/server-entrypoint.sh
        volumes:
            - ./project:/app/project
            - ./data/web/static:/app/data/web/static
            - ./data/web/media:/app/data/web/media
        expose:
            - 8000     
        env_file:
            - ./dotenv_files/.env
    worker:
        restart: always
        build:
            context: .
            dockerfile: ./Dockerfile
        entrypoint: /app/docker/project/worker-entrypoint.sh
        volumes:
            - ./data/web/static:/app/data/web/static
            - ./data/web/media:/app/data/web/media
        env_file:
            - ./dotenv_files/.env
        depends_on:
            - server
            - redis
    redis:
        restart: always
        image: redis:7.0.5-alpine 
        expose:
            - 6379
    db:
        image: postgres:latest
        restart: always
        volumes:
            - ./data/db/data:/var/lib/postgresql/data
        env_file:
            - ./dotenv_files/.env
        expose:
            - 5432
