# Generated by Django 4.2.7 on 2023-11-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='assisted_in',
            field=models.DateField(blank=True, null=True),
        ),
    ]
